
###
GET http://localhost:3000/hello
Content-Type: application/json



###
POST http://localhost:3000/game/startGame
Content-Type: application/json

{
	"userId": "Jan"
}


###
POST http://localhost:3000/game/round/playForCash
Content-Type: application/json

{
	"userId": "Jan",
	"betAmount": 19
}
