

###
POST http://localhost:3000/game/startGame
Content-Type: application/json

{
	"userId": "Jan"
}


###
POST http://localhost:3000/game/round/playForCash
Content-Type: application/json

{
	"userId": "Jan",
	"betAmount": 10
}


###
POST http://localhost:3000/game/round/playForFree
Content-Type: application/json

{
	"userId": "Jan",
	"betAmount": 5
}
