

###
POST http://localhost:3000/game/startGame
Content-Type: application/json

{
	"userId": "Jan"
}


###
POST http://localhost:3000/game/round/playForCash
Content-Type: application/json

{
	"userId": "Jan",
	"betAmount": 5
}


###
POST http://localhost:3000/game/round/playForFree
Content-Type: application/json

{
	"userId": "Jan",
	"betAmount": 5
}


###
GET http://localhost:3000/game-history/user/Jan
Content-Type: application/json

###
GET http://localhost:3000/game-history/gameId/0
Content-Type: application/json


###
GET http://localhost:3000/game-history/roundId/2
Content-Type: application/json



